#!/bin/bash
# input values: 
# 1.) Input Name
# 2.) Input Port
# 
# Usage: Add-Input MyInput 515

GRAYLOG_PATH="/opt/graylog"
COMPOSE_FILE=${GRAYLOG_PATH}/docker-compose.yaml
STREAM_CONF=${GRAYLOG_PATH}/nginx1/stream.conf
INPUT_NAME=${1}
INPUT_PORT=${2}

while [[ ${INPUT_NAME} == "" ]]
do
    read -p "[INPUT] - PLEASE ASSIGN A VALID PORT NAME TO YOUR INPUT: " INPUT_NAME
done

while [[ (${INPUT_PORT} -lt 514) || ( ${INPUT_PORT} -gt 65535) ]]
do
    read -p "[INPUT] - PLEASE ASSIGN A VALID PORT NUMBER TO YOUR INPUT: " INPUT_PORT
done

echo "[INFO] - CREATING INPUT ${INPUT_NAME^^} ON PORT ${INPUT_PORT} "

sudo sed -i "s/# Additional Input Ports/# Additional Input ${INPUT_NAME} created by ${USER} on $(date) \n      - ${INPUT_PORT}:${INPUT_PORT}\n      - ${INPUT_PORT}:${INPUT_PORT}\/udp\n      # Additional Input Ports/g" ${COMPOSE_FILE}

sudo sed -i "s/# ADDITIONAL UPSTREAM ENTRY/# Additional Upstream ${INPUT_NAME} created by ${USER} on $(date) \nupstream graylog-${INPUT_NAME^^} {\n    zone graylog-${INPUT_NAME^^} 64k;\n    least_conn;\n    server graylog1:${INPUT_PORT};\n    server graylog2:${INPUT_PORT};\n}\n\n# ADDITIONAL UPSTREAM ENTRY/g" ${STREAM_CONF}

sudo sed -i "s/# ADDITIONAL SERVER ENTRY/# Additional Server ${INPUT_NAME} created by ${USER} on $(date) \nserver {\n    listen ${INPUT_PORT};\n    listen ${INPUT_PORT} udp;\n    proxy_pass graylog-${INPUT_NAME^^};\n}\n\n# ADDITIONAL SERVER ENTRY/g" ${STREAM_CONF}

echo "[INFO] - RESTARTING REVERSE PROXY CONTAINER NGINX1 "
sudo docker compose -f ${GRAYLOG_PATH}/docker-compose.yaml restart nginx1 2>/dev/null >/dev/null

exit