#!/bin/bash
#
# expected Value: 
# 1.) Input Port
# 
# Usage: 
# Add a single Input Port: Add-InputPort 515
# Add multiple Input Ports: Add-InputPort "515 516 517"

sudo date >/dev/null

read -p "[INPUT] - MOVING FORWARD WILL CAUSE A SHORT SERVICE INTERRUPTION [yes/no]: " CONSENT
CONSENT=${CONSENT:-yes}

if [[ ${CONSENT} != "yes" ]]
then
    echo "[INFO] - SCRIPT EXECUTION INTERRUPTED, EXIT " | logger -p user.info -e -t GRAYLOG-HELPER
    echo "[INFO] - SCRIPT EXECUTION INTERRUPTED, EXIT "
    exit
fi 

GRAYLOG_PATH="/opt/graylog"
COMPOSE_FILE=${GRAYLOG_PATH}/docker-compose.yaml
STREAM_CONF=${GRAYLOG_PATH}/nginx1/stream.conf
INPUT_PORT="${1}"

while [[ (${INPUT_PORT} -lt 514) || (${INPUT_PORT} -gt 65535) || (${INPUT_PORT} == "") ]]
do
    read -p "[INPUT] - PLEASE ASSIGN A VALID INPUT_PORT NUMBER(S) TO YOUR INPUT: " INPUT_PORT
done
    
sudo cp ${COMPOSE_FILE} ${COMPOSE_FILE}.bak
sudo cp ${STREAM_CONF} ${STREAM_CONF}.bak

for PORT in ${INPUT_PORT}
do 
    CHECK_INPUT_PORT=$(grep -ow ${PORT}:${PORT}/udp ${COMPOSE_FILE})

    if [[ "${CHECK_INPUT_PORT}" == "${PORT}:${PORT}/udp" ]]
    then
        echo "[INFO] - CREATE INPUT ON PORT ${PORT}, HANG ON "
        echo "[INFO] - CREATE INPUT ON PORT ${PORT} " | logger -p user.info -e -t GRAYLOG-HELPER

        sudo sed -i "s/# Additional Input Ports/# Input ${PORT}:${PORT} created by ${USER} on $(date) \n      - ${PORT}:${PORT}\n      - ${PORT}:${PORT}\/udp\n      # Additional Input Ports/g" ${COMPOSE_FILE}
        wait
        sudo sed -i "s/# ADDITIONAL UPSTREAM ENTRY/# Upstream for Port ${PORT} created by ${USER} on $(date) \t\t\t#::${PORT}\nupstream graylog-${PORT} {\t\t\t\t\t\t\t\t\t\t#::${PORT}\n    zone graylog-${PORT} 64k ; \t\t\t\t\t\t\t\t\t#::${PORT}\n    least_conn; \t\t\t\t\t\t\t\t\t\t#::${PORT}\n    server graylog1:${PORT}; \t\t\t\t\t\t\t\t\t#::${PORT}\n    server graylog2:${PORT}; \t\t\t\t\t\t\t\t\t#::${PORT}\n} \t\t\t\t\t\t\t\t\t\t\t\t#::${PORT}\n# ADDITIONAL UPSTREAM ENTRY/g" ${STREAM_CONF}
        wait
        sudo sed -i "s/# ADDITIONAL SERVER ENTRY/# Server for Port ${PORT} created by ${USER} on $(date) \t\t\t#::${PORT}\nserver { \t\t\t\t\t\t\t\t\t\t\t#::${PORT}\n    listen ${PORT}; \t\t\t\t\t\t\t\t\t\t#::${PORT}\n    listen ${PORT} udp; \t\t\t\t\t\t\t\t\t\t#::${PORT}\n    proxy_pass graylog-${PORT}; \t\t\t\t\t\t\t\t\t#::${PORT}\n} \t\t\t\t\t\t\t\t\t\t\t\t#::${PORT}\n# ADDITIONAL SERVER ENTRY/g" ${STREAM_CONF}
    else
        echo "[INFO] - PORT ${PORT} HAS ALREADY BEEN PUBLISHED ON THIS SYSTEM"
        echo "[INFO] - PORT ${PORT} HAS ALREADY BEEN PUBLISHED ON THIS SYSTEM" | logger -p user.info -e -t GRAYLOG-HELPER
        exit
    fi
done 

echo "[INFO] - RESTART REVERSE PROXY CONTAINER NGINX1 " | logger -p user.info -e -t GRAYLOG-HELPER
sudo docker compose -f ${GRAYLOG_PATH}/docker-compose.yaml down nginx1 2>/dev/null >/dev/null
sudo docker compose -f ${GRAYLOG_PATH}/docker-compose.yaml up -d nginx1 2>/dev/null >/dev/null
wait
ERROR_RESTART=$(sudo docker compose -f ${GRAYLOG_PATH}/docker-compose.yaml logs nginx1 | tail -n10 | grep -ow emerg | tail -n1)

if [[ ${ERROR_RESTART} == "emerg" ]]
then
    echo $(date) | sudo tee -a ${COMPOSE_FILE} 2>/dev/null
    echo $(date) | sudo tee -a ${STREAM_CONF} 2>/dev/null
    sudo cp ${COMPOSE_FILE} ${COMPOSE_FILE}.debug
    sudo cp ${STREAM_CONF} ${STREAM_CONF}.debug
    sudo cp ${COMPOSE_FILE}.bak ${COMPOSE_FILE}
    sudo cp ${STREAM_CONF}.bak ${STREAM_CONF}

    sudo docker compose -f ${GRAYLOG_PATH}/docker-compose.yaml down nginx1 2>/dev/null >/dev/null
    sudo docker compose -f ${GRAYLOG_PATH}/docker-compose.yaml up -d nginx1 2>/dev/null >/dev/null

    echo "[INFO] - AN ERROR OCCURED DURING THE CONFIGURATION, SYSTEM WAS RESET TO STANDARD VALUES"
    echo "[INFO] - AN ERROR OCCURED DURING THE CONFIGURATION, SYSTEM WAS RESET TO STANDARD VALUES" | logger -p user.info -e -t GRAYLOG-HELPER
else
    echo "[INFO] - SUCCESSFULLY CREATED INPUT ON PORT(S) ${INPUT_PORT} "
    echo "[INFO] - SUCCESSFULLY CREATED INPUT ON PORT(S) ${INPUT_PORT} " | logger -p user.info -e -t GRAYLOG-HELPER
fi

exit