#!/bin/bash
#
# expected Values: 
# 1.) Input Port
# 
# Usage: 
# Remove a single Input Port: Remove-InputPort 515
# Remove multiple Input Ports: Remove-InputPort "515 516 517"

GRAYLOG_PATH="/opt/graylog"
COMPOSE_FILE=${GRAYLOG_PATH}/docker-compose.yaml
STREAM_CONF=${GRAYLOG_PATH}/nginx1/stream.conf
INPUT_PORT="${1}"

for PORT in ${INPUT_PORT}
do
    while [[ ${PORT} == "" ]]
    do
        read -p "[INPUT] - PLEASE DEFINE THE PORT NUMBER(S) OF THE INPUT YOU WANT TO DELETE: " PORT
    done

    echo "[INFO] - REMOVING INPUT ON PORT ${PORT} "
    echo "[INFO] - REMOVING INPUT ON PORT ${PORT} " | logger -p user.info -e -t GRAYLOG-HELPER

    sudo cp ${COMPOSE_FILE} ${COMPOSE_FILE}.bak
    sudo cp ${STREAM_CONF} ${STREAM_CONF}.bak

    grep -vwE ${PORT}:${PORT} ${COMPOSE_FILE} | sudo tee ${COMPOSE_FILE} 2>/dev/null >/dev/null
    wait
    grep -vwE ::${PORT} ${STREAM_CONF} | sudo tee ${STREAM_CONF} 2>/dev/null >/dev/null
    wait
    grep -vwE ::${PORT} ${STREAM_CONF} | sudo tee ${STREAM_CONF} 2>/dev/null >/dev/null

done

echo "[INFO] - RESTART REVERSE PROXY CONTAINER NGINX1 " | logger -p user.info -e -t GRAYLOG-HELPER
sudo docker compose -f ${GRAYLOG_PATH}/docker-compose.yaml down nginx1 2>/dev/null >/dev/null
sudo docker compose -f ${GRAYLOG_PATH}/docker-compose.yaml up -d nginx1 2>/dev/null >/dev/null
wait
ERROR_RESTART=$(sudo docker compose -f ${GRAYLOG_PATH}/docker-compose.yaml logs nginx1 | tail -n10 | grep -ow emerg | tail -n1)

if [[ ${ERROR_RESTART} == "emerg" ]]
then
    echo $(date) | sudo tee -a ${COMPOSE_FILE} 2>/dev/null
    echo $(date) | sudo tee -a ${STREAM_CONF} 2>/dev/null
    sudo cp ${COMPOSE_FILE} ${COMPOSE_FILE}.debug
    sudo cp ${STREAM_CONF} ${STREAM_CONF}.debug
    sudo cp ${COMPOSE_FILE}.bak ${COMPOSE_FILE}
    sudo cp ${STREAM_CONF}.bak ${STREAM_CONF}

    sudo docker compose -f ${GRAYLOG_PATH}/docker-compose.yaml down nginx1 2>/dev/null >/dev/null
    sudo docker compose -f ${GRAYLOG_PATH}/docker-compose.yaml up -d nginx1 2>/dev/null >/dev/null

    echo "[INFO] - AN ERROR OCCURED DURING THE CONFIGURATION, SYSTEM WAS RESET TO STANDARD VALUES"
    echo "[INFO] - AN ERROR OCCURED DURING THE CONFIGURATION, SYSTEM WAS RESET TO STANDARD VALUES" | logger -p user.info -e -t GRAYLOG-HELPER
else
    echo "[INFO] - SUCCESSFULLY REMOVED INPUT ON PORT(S) ${INPUT_PORT} "
    echo "[INFO] - SUCCESSFULLY REMOVED INPUT ON PORT(S) ${INPUT_PORT} " | logger -p user.info -e -t GRAYLOG-HELPER
fi
exit
