#!/bin/bash
#
# expected Values: 
# 1.) Input Port
# 
# Usage: Remove 515

GRAYLOG_PATH="/opt/graylog"
COMPOSE_FILE=${GRAYLOG_PATH}/docker-compose.yaml
STREAM_CONF=${GRAYLOG_PATH}/nginx1/stream.conf
INPUT_NAME="additional"
INPUT_PORT=${1}

echo "[INFO] - REMOVING INPUT ON PORT ${INPUT_PORT} " | logger -p user.info -e -t GRAYLOG-HELPER

sudo cp ${COMPOSE_FILE} ${COMPOSE_FILE}.bak
sudo cp ${STREAM_CONF} ${STREAM_CONF}.bak

grep -vwE ${INPUT_PORT}:${INPUT_PORT} ${COMPOSE_FILE} | sudo tee ${COMPOSE_FILE}

sudo sed -i "s/# Upstream ${INPUT_NAME^}:${INPUT_PORT} created by [.]\+ on [.]\+ \nupstream graylog-${INPUT_NAME,,}-${INPUT_PORT} {\n    zone graylog-${INPUT_NAME,,}-${INPUT_PORT} 64k;\n    least_conn;\n    server graylog1:${INPUT_PORT};\n    server graylog2:${INPUT_PORT};\n}//g" ${STREAM_CONF}
sudo sed -i "s/# Server ${INPUT_NAME^}:${INPUT_PORT} created by [.]\+ on [.]\+ \nserver {\n    listen ${INPUT_PORT};\n    listen ${INPUT_PORT} udp;\n    proxy_pass graylog-${INPUT_NAME,,}-${INPUT_PORT};\n}\n\n# ADDITIONAL SERVER ENTRY//g" ${STREAM_CONF}

echo "[INFO] - RESTARTING REVERSE PROXY CONTAINER NGINX1 " | logger -p user.info -e -t GRAYLOG-HELPER
sudo docker compose -f ${GRAYLOG_PATH}/docker-compose.yaml restart nginx1 2>/dev/null >/dev/null

ERROR_RESTART=$(sudo docker compose logs nginx1 | tail -n10 | grep -ow emerg | tail -n1)

if [[ ${ERROR_RESTART} == "emerg" ]]
then
    sudo cp ${COMPOSE_FILE}.bak ${COMPOSE_FILE}
    sudo cp ${STREAM_CONF}.bak ${STREAM_CONF}
    sudo docker compose -f ${GRAYLOG_PATH}/docker-compose.yaml restart nginx1 2>/dev/null >/dev/null

    echo "[INFO] - AN ERROR OCCURED DURING THE CONFIGURATION, SYSTEM WAS RESET TO STANDARD VALUES"
exit