#!/bin/bash
#
# Usage: 
# Reset System to Install-Ready Status: Reset-GraylogInstallation

sudo date >/dev/null

sudo apt purge graylog-sidecar -y
sudo rm -rf /opt/graylog

grep -vwE PATH /etc/bash.bashrc | sudo tee /etc/bash.bashrc 2>/dev/null >/dev/null

echo "[INFO] - SYSTEM CAN BE USED FOR ANOTHER CLEAN GRAYLOG INSTALLATION"

exit