#!/bin/bash
#
# Usage: 
# Reset System to Install-Ready Status: Reset-GraylogInstallation "/opt/graylog"
GRAYLOG_PATH=$1

sudo date >/dev/null

read -p "[INPUT] - MOVING FORWARD WILL DELETE YOUR ENTIRE GRAYLOG STACK INCLUDING CONFIGURATION AND LOG DATA AS WELL AS RESTART THE SYSTEM [no]: " CONSENT
CONSENT=${CONSENT:-no}

if [[ ${CONSENT} != "yes" ]]
then
    echo "[INFO] - SCRIPT EXECUTION INTERRUPTED, NO DATA DELETED, EXIT " | logger -p user.info -e -t GRAYLOG-HELPER
    echo "[INFO] - SCRIPT EXECUTION INTERRUPTED, NO DATA DELETED, EXIT "
    exit
fi 

if [[ ${GRAYLOG_PATH}  == "" ]]
then
    GRAYLOG_PATH="/opt/graylog"
    BACKUP_SCRIPT="/etc/cron.daily/Create-ConfigurationDump"

    sudo docker compose -f ${GRAYLOG_PATH}/docker-compose.yaml down 2>/dev/null >/dev/null
    wait

    sudo apt purge graylog-sidecar -y 2>/dev/null >/dev/null
    wait

    sudo rm -rf ${GRAYLOG_PATH} >/dev/null
    sudo rm ${BACKUP_SCRIPT}

    grep -vwE PATH /etc/bash.bashrc | sudo tee /etc/bash.bashrc 2>/dev/null >/dev/null
    grep -vwE completion-ignore-case /etc/bash.bashrc | sudo tee /etc/bash.bashrc 2>/dev/null >/dev/null

    echo "[INFO] - SYSTEM IS NOW CLEAN AND WILL BE RESTARTED NOW BY ${USER^^}" 
    echo "[INFO] - SYSTEM IS NOW CLEAN AND WILL BE RESTARTED NOW BY ${USER^^}" | logger -p user.info -e -t GRAYLOG-HELPER

    sudo reboot

fi

exit
