#!/bin/bash
#
# This Script will restore the latest Configuration Backup from /opt/graylog/configuration_dump
#
# Usage: 
# Restore-ConfigurationDump

sudo date >/dev/null

GRAYLOG_PATH="/opt/graylog"
BACKUP_DIRECTORY="configuration_dump"
RESTORE_DIRECTORY="/tmp"
RESTORE_DUMP_FILE=$(ls ${GRAYLOG_PATH}/${BACKUP_DIRECTORY}/ | grep -i dump | sort -r | head -n1)

sudo tar -xzf "${GRAYLOG_PATH}/${BACKUP_DIRECTORY}/${RESTORE_DUMP_FILE}" -C /tmp
sudo docker compose -f ${GRAYLOG_PATH}/docker-compose.yaml exec mongodb1 mongorestore --host=localhost --port=27017 --db graylog --dir ${RESTORE_DIRECTORY}/${GRAYLOG_PATH}/${BACKUP_DIRECTORY}/${RESTORE_DUMP_FILE} --quiet
sudo rm -rf "${RESTORE_DIRECTORY}/${GRAYLOG_PATH}/${BACKUP_DIRECTORY}/${RESTORE_DUMP_FILE}"

if [[ ${USER} == "" ]]
then
  USER="GRAYLOG SYSTEM"
fi

echo "[INFO] - GRAYLOG CONFIGURATION RESTORE SUCCESSFULLY FINISHED BY ${USER^^}" 
echo "[INFO] - GRAYLOG CONFIGURATION RESTORE SUCCESSFULLY FINISHED BY ${USER^^} | logger -p user.info -e -t GRAYLOG-HELPER"

exit
